// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_letterboxd_username_ from "./routes/api/letterboxd/[username].ts";
import * as $index from "./routes/index.tsx";
import * as $App from "./islands/App.tsx";
import * as $GridPicker from "./islands/GridPicker.tsx";
import * as $ResultCardActions from "./islands/ResultCardActions.tsx";
import * as $forms_CollageForm from "./islands/forms/CollageForm.tsx";
import * as $forms_GenerateButton from "./islands/forms/GenerateButton.tsx";
import * as $forms_TitlesAndRatingToggle from "./islands/forms/TitlesAndRatingToggle.tsx";
import * as $forms_UsernameInput from "./islands/forms/UsernameInput.tsx";
import * as $modals_CopiedModal from "./islands/modals/CopiedModal.tsx";
import * as $modals_DownloadModal from "./islands/modals/DownloadModal.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/letterboxd/[username].ts": $api_letterboxd_username_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/App.tsx": $App,
    "./islands/GridPicker.tsx": $GridPicker,
    "./islands/ResultCardActions.tsx": $ResultCardActions,
    "./islands/forms/CollageForm.tsx": $forms_CollageForm,
    "./islands/forms/GenerateButton.tsx": $forms_GenerateButton,
    "./islands/forms/TitlesAndRatingToggle.tsx": $forms_TitlesAndRatingToggle,
    "./islands/forms/UsernameInput.tsx": $forms_UsernameInput,
    "./islands/modals/CopiedModal.tsx": $modals_CopiedModal,
    "./islands/modals/DownloadModal.tsx": $modals_DownloadModal,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
